trigger: none
pr: none

resources:
 repositories:
   #https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops
   - repository: github1 #referencename
     type: github #typeofrepository
     name: anandazaugust/tf-template  #actualreponame
     endpoint: mygithubfeb19 #serviceconnectionname
     ref: refs/heads/feature1
  
extends:  # if this is not there, it will not know which template to call in the repo
     template: pipeline_cd.yaml@github1 #referencename 